name: Testing Checks
description: Various testing related checks

# Runs on pushes to a pull request, and will cancel previous runs if
# another push is made while checks are still running from previous pushes
on: pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Unit-Testing:
    name: Unit Testing
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Tests with Coverage
        run: npm run coverage
